### ISSUE TITLE
How to get nvidia-driver-396?

### ISSUE THREAD

**Issue by saskra** [pplcc/ubuntu-tensorflow-pytorch-setup#1]
> Select the nvidia-driver-396 and click Apply Changes

Whenever I try to do this step, it just switches back to nvidia-driver-390. This did not happen to you?

**Comment by pplcc** [comment]
Hi!

It didn't happen when I performed the set up on a freshly installed Ubuntu 18.04.1. I performed the setup twice following exactly these steps, just to be sure that I didn't miss anything.

However I remember that earlier during my Odyssey I encountered that situation. I guess you may have tried to install the 396 driver earlier and you didn't install the kernel sources. You may try:

```
sudo apt install nvidia-kernel-source-396
sudo apt install nvidia-driver-396
sudo restart now
```

An then try to select the driver...

Keep me posted!

Greetings!

Peter

**Comment by saskra** [comment]
Yes, thanks a lot - the kernel-source has been the missing part. Now I can finally use the correct cuDNN version with Anaconda. :-)
